<?php


class Batiment extends Manager
{


    function  __construct()
    {
        $this->tableName="batiment";
    }
    public function findAll()
    {
        return parent::findAll(); // TODO: Change the autogenerated stub
    }

}