<?php
ini_set('display_errors', 1);

require_once("../libs/Manager.php");

class Etudiant extends Manager
{
    public function __construct()
    {
        $this->tableName = "etudiant";
    }

    public function findAll()
    {
        return parent::findAll(); //appele  de la function fundALL() de menager et recuPération des Etudiant
    }

    function enregistrerEtudiant($prenom, $nom, $matricule, $telephone, $email, $chambre, $adresse, $bourse, $date_naiss)
    {
        return parent::enregistrerEtudiant($prenom, $nom, $matricule, $telephone, $email, $chambre, $adresse, $bourse, $date_naiss); // TODO: Change the autogenerated stub
    }
    public function EtudiantNoChambre($prenom, $nom, $matricule, $telephone, $email, $adresse, $bourse, $date_naiss)
    {
        return parent::EtudiantNoChambre($prenom, $nom, $matricule, $telephone, $email, $adresse, $bourse, $date_naiss); // TODO: Change the autogenerated stub
    }

}