<?php


class TypeChambre extends Manager
{
public function __construct()
{
    $this->tableName="type_chambre";

}
public function findAll()
{
    return parent::findAll(); // TODO: Change the autogenerated stub
}

}